name: CD

on:
  push:
    branches: [prod]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: build docker image
        run: |
          docker build -t assignment4 .

      - name: run docker container
        run: |
          docker run assignment4